var app =  TestedApps.Items(0);
var wnd = Aliases.Passport_POS.wndApolloRuntimeContentWindow;
var passportPOS = wnd.passportposPassportpos1;
var userNameTxtBox =passportPOS.textinputTxtusername;
var passwordTxtBox =passportPOS.textinputInputfield;
var loginBtn =passportPOS.buttonLoginbtn;
var POSGroup = passportPOS.POSGroup;
var defaultGroupName = "Mango New";
var expectedBuildText = "© 2018 accesso Technology Group plc build 5.0.9 - Service Pack 1";




//var homeButton =passportPOS.homeButton;
var homeButton =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.groupHeadergroup.groupGroup105.homeButton;
//var logOutButton = passportPOS.groupGroup3.groupContentgroup.mainviewMainview33.topcontrolbarTopcontrolbar97.groupControlbar.groupHgroup130.logOutButton;
var logOutButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.groupHeadergroup.groupGroup105.logOutButton;
//var selectDirectoryButton=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.groupGroup3.groupContentgroup.mainviewMainview33.topcontrolbarTopcontrolbar97.groupControlbar.groupHgroup130.selectDirectoryButton;
var selectDirectoryButton=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.groupHeadergroup.groupGroup105.selectDirectoryButton;

var footerBuildNumber = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.bottomcontrolbarBottomcontrolbar.groupGroup133.groupHgroup134.footerBuildNumber;
var bottomPOSOfflineImage = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.bottomcontrolbarBottomcontrolbar.groupGroup133.groupHgroup137.imageForcedisconnectedimage;
var bottomPOSOnlineImage = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.bottomcontrolbarBottomcontrolbar.groupGroup133.groupHgroup137.imageConnectedimage;


//var Keyword_Listgroup = passportPOS.Keyword_Listgroup;
//var Keyword_Listgroup = passportPOS.Keyword_Listgroup_u;
//var Keyword_Listgroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.keywordlistview.groupKeywordsgrp.groupKeywordlistgroup.Keyword_Listgroup_updated;
var Keyword_Listgroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.keywordlistview.groupKeywordsgrp.groupKeywordlistgroup.Keyword_Listgroup_updated;
var groupClosekeywordgrp =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.keywordlistview.groupKeywordsgrp.groupClosekeywordgrp;
var keyWordgrpscrollButtons =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.keywordlistview.groupKeywordsgrp.groupClosekeywordgrp.keyWordgrpscrollButtons;
var keyWorddown = keyWordgrpscrollButtons.keyWorddown;
var keyWordup = keyWordgrpscrollButtons.keyWordup;
//var finilizeOrder_button = passportPOS.finilizeOrder_button;


var finilizeOrder_button = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.carttotalsPoscarttotals.groupVgroup613.groupTotalgroup.selectablebuttonFinalizebutton;

var groupXmccollectionscrollgroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupXmccollectionscrollgroup;
var selectablebuttonClosebutton = groupXmccollectionscrollgroup.groupXmccollectionbuttonsgroup.selectablebuttonClosebutton;
var selectablebuttonScrolldown = groupXmccollectionscrollgroup.groupXmccollectionbuttonsgroup.listscrollerbuttonsScrollbuttonc.selectablebuttonScrolldown;
var selectablebuttonScrollup =  groupXmccollectionscrollgroup.groupXmccollectionbuttonsgroup.listscrollerbuttonsScrollbuttonc.selectablebuttonScrollup;

var addToCart_button = passportPOS.addToCart_button;
/*
//Updated to Menu Icon
var MainMenuIconGroup =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.groupGroup3.groupContentgroup.mainviewMainview33.topcontrolbarTopcontrolbar97.MainMenuIconGroup;
var PointOfSaleIcon = MainMenuIconGroup.groupHgroup107.groupVgroup108.PointOfSaleIcon;
var GroupsIcon = MainMenuIconGroup.groupHgroup107.groupVgroup116.GroupsIcon;
var SupportManagerIcon = MainMenuIconGroup.groupHgroup107.groupVgroup124.SupportManagerIcon;
var PassProcessingIcon = MainMenuIconGroup.groupHgroup107.groupVgroup128.PassProcessingIcon;
var ExchangeIcon = MainMenuIconGroup.groupHgroup107.groupVgroup132.ExchangeIcon;
*/
//  Home Menu
var PointOfSale_MainMenu= Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonPointof;
var Groups_MainMenu =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonGroupsm;
var SupportManger_MainMenu = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonSupport
var SupportManager_MainMenu =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonSupport
var PassProcessing_MainMenu= Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonPasspro;
var Exchange_MainMenu= Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonExchang
var SupportManger_MainMenu = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.MainMenu.groupModulebuttongroup.topcontrolbarmodulebuttonSupport
//var allPackages = passportPOS.allPackages;
//var allPackages = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupPackagexmcgroup.packagelistview.listPackagelistgroup;
var allPackages = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupLeftgroupinnergroup.groupPackagesxmcgroup.packagelistview.allPackages;
                  
var subWindowDateChooser = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupLeftgroupinnergroup.groupPackagesxmcgroup.groupDatetimeformgroup.groupGroup532.datetimeform.groupHgroup542.subWindowDateChooser; 

//var subWindowNextButton =  datetimeformSubWindow.subWindowNextButton;
 
var subWindowNextButton = passportPOS.addToCart_button;

//var PaymentType_BalanceLabel=passportPOS.PaymentType_BalanceLabel; 
var PaymentType_BalanceLabel=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2733.groupVgroup2735.groupGroup2746.Remaining_BalanceLabel;

//Select payment method
//var selectPaymentTypeDropDown=passportPOS.selectPaymentTypeDropDown;
var selectPaymentTypeDropDown=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupHgroup2658.selectPaymentTypeDropDown;


//var  reservationWndConvertToPurchaseButton = passportPOS.qty_1;
//var  reservationWndConvertToReservationButton = passportPOS.qty_0;
//var editOrder_SettlementWindow = passportPOS.editOrder_SettlementWindow;
var  reservationWndConvertToPurchaseButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup5348.groupLeftgroup.groupHgroup5388.selectablebuttonConverttopurchas;
var  reservationWndConvertToReservationButton =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup5348.groupLeftgroup.groupHgroup5388.selectablebuttonConverttoreserva;
var editOrder_SettlementWindow =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup5348.groupLeftgroup.groupHgroup5388.selectablebuttonEditcartbutton;


// Variables for SubWindow Selaction
var datetimeformSubWindow = subWindowDateChooser;
var availableTimedatagroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupLeftgroupinnergroup.groupPackagesxmcgroup.groupDatetimeformgroup.groupGroup532.datetimeform.groupHgroup542.timechooser.groupVgroup541.availableTimedatagroup;
var subWindowSubPackageWindow = wnd.datetimeformSubWindow.subWindowSubPackageWindow;
var subWindowAvailableTimeWindow = wnd.datetimeformSubWindow.subWindowAvailableTimeWindow;
var buttonClosebutton = wnd.datetimeformSubWindow.buttonClosebutton;
var capacityGroup = availableTimedatagroup.listitemComAccessoComponentsCapa.groupHgroup2454.capacityGroup;
var groupDateonlycapacitygroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupLeftgroupinnergroup.groupPackagesxmcgroup.groupDatetimeformgroup.groupGroup532.groupXmcheadergroup.groupDateonlycapacitygroup;
var scrollbarVerticalscrollbar = wnd.datetimeformSubWindow.subWindowSubPackageWindow.scrollbarVerticalscrollbar;


// PackageQuantitySelector
var PackageQuantitySelector = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.groupLeftgroupinnergroup.packagequantityselector;
var selectablebuttonClearbutton = PackageQuantitySelector.groupButtongroup.selectablebuttonClearbutton;
var selectablebuttonQtybtn0 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn0;
var selectablebuttonQtybtn1 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn1;
var selectablebuttonQtybtn2 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn2;
var selectablebuttonQtybtn3 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn3;
var selectablebuttonQtybtn4 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn4;
var selectablebuttonQtybtn5 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn5;
var selectablebuttonQtybtn6 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn6;
var selectablebuttonQtybtn7 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn7;
var selectablebuttonQtybtn8 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn8;
var selectablebuttonQtybtn9 = PackageQuantitySelector.groupButtongroup.selectablebuttonQtybtn9;
var labelQuantitylabel = PackageQuantitySelector.groupButtongroup.groupGroup452.labelQuantitylabel;

//var AssignNewBarCode_Button                        = passportPOS.TotalBalanceLabel_orderDetails.PassHolderSearch_SeasonPassIDWindow.AssignNewBarCode_Button;

var AssignNewBarCode_Button  = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupHgroup4386.AssignNewBarCode_Button;

var SessionPassDataGrid =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.SessionPassDataGrid;
var sessionPassOrderID = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.SessionPassDataGrid.scroller.grid.accdatagridskininnerclass9Accdat.gridlayerRendererlayer.sessionPassOrderID;
var OrderHistory_Scroller_OrderID_Row1             = sessionPassOrderID;


var selectablebuttonBackbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassfulfillmentviewSeasonp.groupHgroup5278.groupVgroup5279.groupHgroup5281.selectablebuttonBackbtn;
var selectablebuttonCameraselectbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassfulfillmentviewSeasonp.groupHgroup5278.groupVgroup5279.groupHgroup5281.selectablebuttonCameraselectbtn;
var selectablebuttonPreviewbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassfulfillmentviewSeasonp.groupHgroup5278.groupVgroup5279.groupHgroup5281.selectablebuttonPreviewbtn;
var selectablebuttonPrintbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassfulfillmentviewSeasonp.groupHgroup5278.groupVgroup5279.groupHgroup5281.selectablebuttonPrintbtn;
var selectablebuttonSearchbtn =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassfulfillmentviewSeasonp.groupHgroup5278.groupVgroup5279.groupHgroup5281.selectablebuttonSearchbtn;

//var PrintPreview_Button                            = passportPOS.qty_2;
var PrintPreview_Button                            = selectablebuttonPreviewbtn;
var PrintPreview_Window                            = wnd.PrintPreviewWindow;
var PrintPreview_Closebutton                       =PrintPreview_Window.buttonClosebutton;


//Directory
/*
var Directory_OrderHistory =passportPOS.Directory_OrderHistory;
var Directory_Tracker = passportPOS.Directory_Tracker;
var Directory_NoSale = passportPOS.Directory_NoSale;
var Directory_GoOffline =passportPOS.buttonGoOffline;
var Directory_CancelOrder = passportPOS.Directory_CancelOrder;
var Directory_ChangePassword = passportPOS.Directory_ChangePassword;
var Directory_PrintExchangeQueue = passportPOS.Directory_PrintExchangeQueue;
var Directory_SendLogs = passportPOS.Directory_SendLogs;
var Directory_TrackerLoggedOn = passportPOS.Directory_TrackerLoggedOn;
var Directory_AutoValidationOnOff = passportPOS.Directory_AutoValidationOnOff;
var Directory_AutoValidationOn = passportPOS.Directory_AutoValidationOn;
var Directory_About = passportPOS.Directory_About;
var Directory_CashLift = passportPOS.Directory_CashLift;
*/
var Directory_OrderHistory =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.settingsmenuSettingsmenu183.groupVgroup186.Directory_OrderHistory;
var Directory_Tracker = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_Tracker;
var Directory_NoSale = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.settingsmenuSettingsmenu183.groupVgroup186.Directory_NoSale;
var Directory_GoOffline =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_Offline;
var slidetoggleOfflineslidetoggle = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.settingsmenuSettingsmenu183.groupVgroup186.groupToggleofflinegroup.slidetoggleOfflineslidetoggle;
var Directory_CancelOrder = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_CancelOrder;
var Directory_ChangePassword = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_ChangePassword;
var Directory_PrintExchangeQueue = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_PrintExchangeQueue;
var Directory_SendLogs = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_SendLogs;
var Directory_TrackerLoggedOn = passportPOS.Directory_TrackerLoggedOn;
var toggleTrackertoggle =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.settingsmenuSettingsmenu183.groupVgroup186.groupTrackertogglegroup.toggleTrackertoggle;
var Directory_AutoValidationOnOff = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_AutoValidation;
var slidetoggleAutovalidateslidetogg = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.settingsmenuSettingsmenu183.groupVgroup186.groupAutovalidatetogglegroup.slidetoggleAutovalidateslidetogg;
var Directory_AutoValidationOn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_AutoValidation;
var Directory_About = passportPOS.Directory_About;
var Directory_CashLift = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_CashLift;
var D_CashOut = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.D_CashOut;
var Directory_Tracker_OnOff = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.Directory_Tracker_OnOff;




//Refund button
var dateOnConfirmationPage = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.dateOnConfirmationPage;
var Refund_Button = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupButtongroup.cnf_selectablebuttonRefundbutton;
var cnf_selectablebuttonPrintreceiptbutt = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupButtongroup.cnf_selectablebuttonPrintreceiptbutt;
var cnf_selectablebuttonPrintticketsbutt =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupButtongroup.cnf_selectablebuttonPrintticketsbutt;
var cnf_newGroupOrderBtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupButtongroup.cnf_newGroupOrderBtn;

var groupUpdateBuyTicketsButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupcreateviewGroupcreateview26.groupHgroup2680.groupGroup2697.groupVgroup2699.groupHgroup2704.groupUpdateBuyTicketsButton;
var groupsSearchOnUpdate = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupcreateviewGroupcreateview26.groupHgroup2680.groupGroup2697.groupVgroup2699.groupHgroup2704.groupUpdateSearchButton;


//orderpage order details 
var groupCartandcarttotalsgroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup;
var totalOnOrderScreen =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.carttotalsPoscarttotals.groupVgroup613.groupTotalgroup.totalOnOrderScreen;
var subTotalOnOrderScreen = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.carttotalsPoscarttotals.groupVgroup613.groupSubtotalgroup.subTotalOnOrderScreen;
var cartadjustmentsOnOrderScreen= Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.carttotalsPoscarttotals.groupVgroup613.groupHgroup624.groupDetailsgroup.groupVgroup626.groupCartadjustmentgroup.groupGroup628.cartadjustmentsOnOrderScreen;
var feesOnOrderScreen = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.carttotalsPoscarttotals.groupVgroup613.groupHgroup624.groupDetailsgroup.groupVgroup626.groupFeesgroup.groupGroup638.feesOnOrderScreen;
var taxOnOrderScreen= Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.carttotalsPoscarttotals.groupVgroup613.groupHgroup624.groupDetailsgroup.groupVgroup626.groupTaxesgroup.groupGroup633.taxOnOrderScreen;


//orderpage order details- settlement
var orderDetails = passportPOS.TotalBalanceLabel_orderDetails.groupDetailsvgroup;
var cartdetailsCartfeedetails = orderDetails.cartdetailsCartfeedetails;
var orderDetailsCartAdjustment = orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupCartAdjustment.orderDetailsCartAdjustment;
var orderDetailsFees =orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupFees.orderDetailsFees;
var orderDetailsTax =orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupTax.orderDetailsTax;
var orderDetailsMinimumPayment =orderDetails.groupMiniumPayment.orderDetailsMinimumPayment;
var orderDetailsSubTotal =orderDetails.groupSubTotal.orderDetailsSubTotal;
var orderDetailsTotal =orderDetails.groupTotal.orderDetailsTotal;

var selectablebuttonAddnotesbutton =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2503.groupHgroup2505.selectablebuttonAddnotesbutton;
var selectablebuttonAdjustbalancebut =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2503.groupHgroup2505.selectablebuttonAdjustbalancebut;
var selectablebuttonCustomerdetailsb = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2503.groupHgroup2505.selectablebuttonCustomerdetailsb;
var selectablebuttonFinalizebutton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2503.groupHgroup2505.selectablebuttonFinalizebutton;

var confirmationPageTotalREZ = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupGroup6424.carttotalsviewReztotals.groupVgroup6428.scrollerScrollbar.groupDetailsvgroup.groupGroup6447.confirmationPageTotalREZ;
var confirmationPageTotalNormal = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupGroup6424.carttotalsviewOrdertotals.groupVgroup3649.scrollerScrollbar.groupDetailsvgroup.groupGroup3668.confirmationPageTotalNormal;
var confirmationPageSubTotalNormal = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupGroup6424.carttotalsviewOrdertotals.groupVgroup3649.scrollerScrollbar.groupDetailsvgroup.groupGroup3355.confirmationPageSubTotalNormal;



var labelTotal=orderDetailsTotal;
var labelTotal_new=orderDetailsTotal;

// customer details popup
var customerdetailspopup =Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup;
var cdFirstnameti = customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3507.groupHgroup3508.textinputFirstnameti;
var cdLastnameti = Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3507.groupHgroup3511.textinputLastnameti;
var cdHomephoneti = Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3514.groupHgroup3515.textinputHomephoneti
var cdCellphoneti =Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3514.groupHgroup3518.textinputCellphoneti
var cdEmailti = Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3521.textinputEmailti
var cdTxtinput=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3524.calendarpopupDobcal.textinputTxtinput
var cdCheckdisplay =Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupVgroup3506.groupHgroup3524.checkboxOptincheck.groupCheckdisplay
var cdBillingaddressti =Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupBillingAddress.groupBordergroup.groupMaincntr.groupGroup3572.groupHgroup3574.textinputBillingaddressti
var cdBillingcityti=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupBillingAddress.groupBordergroup.groupMaincntr.groupGroup3585.textinputBillingcityti
var cdBillingzipti=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupBillingAddress.groupBordergroup.groupMaincntr.groupGroup3585.textinputBillingzipti
var cdcountriesddBilling=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupBillingAddress.groupBordergroup.groupMaincntr.groupGroup3590.countriesdropdownlistBillingcoun
var cdstateddBilling=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupBillingAddress.groupBordergroup.groupMaincntr.groupGroup3590.statedropdownlistBillingstateddl

var cdShippingaddressti=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupHomeAddress.groupBordergroup.groupMaincntr.groupGroup3540.groupHgroup3542.textinputShippingaddressti
var cdShippingaddressti2=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupHomeAddress.groupBordergroup.groupMaincntr.groupGroup3550.groupHgroup3551.cdShippingaddressti2;
var cdShippingcityti=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupHomeAddress.groupBordergroup.groupMaincntr.groupGroup3553.textinputShippingcityti
var cdShippingzipti=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupHomeAddress.groupBordergroup.groupMaincntr.groupGroup3553.textinputShippingzipti
var cdcountriesddShipping=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupHomeAddress.groupBordergroup.groupMaincntr.groupGroup3558.countriesdropdownlistShippingcou
var cdstateddShipping=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.labeledgroupHomeAddress.groupBordergroup.groupMaincntr.groupGroup3558.statedropdownlistShippingstatedd

var cdCancelbutton=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupHgroup3600.cusDetailsCancelbutton
var cdOkbutton=Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupHgroup3600.cusDetailsOkbutton
 var checkboxUsehomecheck =Aliases.Passport_POS.wndApolloRuntimeContentWindow.customerdetailspopup.groupGroup3489.groupContents.groupGroup3497.groupContentgroup.groupVgroup3505.groupGroup3565.checkboxUsehomecheck;


var TicketBarcodeTextBox = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.TicketBarcodeTextBox;
var alertOneMoreStep =Aliases.Passport_POS.wndApolloRuntimeContentWindow.alertOneMoreStep;
var buttonOkAlertOneMore =Aliases.Passport_POS.wndApolloRuntimeContentWindow.alertOneMoreStep.buttonOkAlertOneMore;
var validatequantityOnTrackerScan =Aliases.Passport_POS.wndApolloRuntimeContentWindow.trackerpopupTrackerScanAndValida.groupGroup5826.groupContents.groupGroup5833.groupContentgroup.groupVgroup5897.validatequantityOnTrackerScan; 


//var Participantlist = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupHgroup19427.groupParticipantlistvgroup.Participantlist;
var Participantlist = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupHgroup19427.listParticipantlist;
                      
//var passHolderScrolldown = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupHgroup955.listscrollerbuttonsScrollbuttonc.passHolderScrolldown;
var passHolderScrolldown = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupButtongroup.listscrollerbuttonsScrollbuttonc.selectablebuttonScrolldown;


var FirstnameField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup23617.groupHgroup23618.FirstnameField;
var FirstNameErrorIndicator = FirstnameField.FirstNameErrorIndicator;
var LastnameField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup23617.groupHgroup23624.LastnameField;
var sessionPassLastNameErrorindicator = LastnameField.sessionPassLastNameErrorindicator;
var MiddleInitialField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup23617.groupHgroup23621.MiddleInitialField;
var SuffixField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7181.groupHgroup7182.SuffixField;
var DateOfBirthfield = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7181.groupHgroup7185.calendarpopupDobcal.DateOfBirthfield;
var AddressField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7196.groupHgroup7197.AddressField;
var Address2Field = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7196.groupHgroup7200.Address2Field;
var EmailField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7225.groupHgroup7226.EmailField;
var PhoneField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7225.groupHgroup7229.PhoneField;
//var GenderField =  Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7181.groupHgroup7193.GenderField;
var GenderField =  Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7181.groupHgroup7193.dropdownlistGenderddl;

var zipCodeField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup4364.groupHgroup4365.groupHgroup4367.zipCodeField;
var cityField = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup4364.groupHgroup4375.cityField;
var stateField  = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup4364.groupHgroup4378.statedropdownlistStateddl.stateField;
var richeditabletextTextdisplay= Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup4439.textareaMemoti;
var Renew_Button =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupHgroup4297.groupExpiregroup.Renew_Button;
var ExpirationDateLabel = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupHgroup4297.groupExpiregroup.ExpirationDateLabel;
var dateOfBirthErrorIndicator = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.scrollerScrollbar.groupVgroup4382.groupVgroup23616.groupHgroup7181.groupHgroup7185.calendarpopupDobcal.DateOfBirthfield.dateOfBirthErrorIndicator;

var confirmationbuttonClearbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.cartviewnewPoscartview.groupVgroup609.groupShoppingcartgrp.selectablebuttonClearcartbutton;

var cash1 =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.cashpaymentformCash.groupBordergroup.groupMaincntr.groupVgroup3646.listQuickcashbuttonlist.listitem1.selectablebutton1;
var cash10  =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.cashpaymentformCash.groupBordergroup.groupMaincntr.groupVgroup3646.listQuickcashbuttonlist.listitem10.selectablebutton10;
var cash100  = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.cashpaymentformCash.groupBordergroup.groupMaincntr.groupVgroup3646.listQuickcashbuttonlist.listitem100.selectablebutton100;
var cash20 = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.cashpaymentformCash.groupBordergroup.groupMaincntr.groupVgroup3646.listQuickcashbuttonlist.listitem20.selectablebutton20;
var cash5 = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.cashpaymentformCash.groupBordergroup.groupMaincntr.groupVgroup3646.listQuickcashbuttonlist.listitem5.selectablebutton5;
var cash50 = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.cashpaymentformCash.groupBordergroup.groupMaincntr.groupVgroup3646.listQuickcashbuttonlist.listitem50.selectablebutton50;



var Hotelguestnameinput = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.Hotelguestnameinput;
var Hotelnamecombobox = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.Hotelnamecombobox;
var Hotelroomnumberinput = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.Hotelroomnumberinput;

var labelCurrentUserName =Aliases.Passport_POS.wndApolloRuntimeContentWindow.trackerpopupTrackerScanAndValida.groupGroup5826.groupContents.groupGroup5833.groupContentgroup.groupVgroup5897.labelConfigmessagelabel;
//var groupCartitemrategrp = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.cartviewnewPoscartview.groupVgroup609.listCartitemlist.listitemObjectCartitemrendererda.groupCartvgroup.listRateslist.listitemObjectCartitemraterender.groupHgroup2257.groupCartitemrategrp;
var cartaddedItemList =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupCartandcarttotalsgroup.cartviewnewPoscartview.groupVgroup609.cartaddedItemList;


var PassHolderLastNameErrorindicator = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupHgroup19427.groupFormgroupinner.seasonpassinformationformSeasonP.groupGroup5926.passholderdetailsformSeasonPassh.scrollerScroller5930.groupGroup5931.bordercontainerBordercontainer59.groupGroup5955.groupVgroup5983.groupHgroup5984.groupGroup5991.textinputLastnameti.bitmap0;
var PassHolderFirstNameErrorindicator =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupHgroup19427.groupFormgroupinner.seasonpassinformationformSeasonP.groupGroup5926.passholderdetailsformSeasonPassh.scrollerScroller5930.groupGroup5931.bordercontainerBordercontainer59.groupGroup5955.groupVgroup5983.groupHgroup5984.groupGroup5985.textinputFirstnameti.bitmap0;

//Payment list items

var paymentlistgroup =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2733.groupVgroup2735.paymentslistPaymentlistgroup.paymentlistgroup;
var paymentListFirstItem = paymentlistgroup.paymentListFirstItem;
var CustomerHeaderLabel = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.groupHeadergroup.groupGroup105.groupCustomergroup.CustomerHeaderLabel;

// PassHolder Search Window
var PassHolder_ResultDataGrid =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassHolder_ResultDataGrid;
var PassHolder_ResultDataGridScroller =  PassHolder_ResultDataGrid.PassHolder_ResultDataGridScroller;
var gridlayerRendererlayer =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassHolder_ResultDataGrid.PassHolder_ResultDataGridScroller.grid.accsppdatagridskininnerclass9Acc.gridlayerRendererlayer;
 
var PassHolder_ResultDataGridScroller_OrderID_Row1 = passportPOS.PassHolder_ResultDataGrid.PassHolder_ResultDataGridScroller.PassHolder_ResultDataGridScroller_OrderID_Row1;
var PassHolder_ResultDataGridScroller_OrderID_Row2 =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassHolder_ResultDataGrid.PassHolder_ResultDataGridScroller.PassHolder_ResultDataGridScroller_OrderID_Row2;
var PassHolder_ResultDataGridScroller_OrderID_Row1_new =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PassHolder_ResultDataGrid.PassHolder_ResultDataGridScroller.PassHolder_ResultDataGridScroller_OrderID_Row1_new;
var PassProcessing_OrderID  = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpasssearchviewSeasonpassse.groupSearchgroup.groupHgroup2116.groupGroup2123.PassProcessing_OrderID;
var copyDataForPass = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.TotalBalanceLabel_orderDetails.copyDataForPass;

var Save_Button                                    = passportPOS.Save_Button;
var Process_Button                                 = passportPOS.Process_Button;
var Pass_Back_Button                               = passportPOS.qty_1;
//var PassHolderSearch_TicketID = passportPOS.PassHolderSearch_TicketID;
var PassHolderSearch_TicketID = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpasssearchviewSeasonpassse.groupSearchgroup.groupHgroup2116.groupGroup4175.textinputBarcodeti;

//var PassHolderSearchClear                          = passportPOS.PassHolderSearchClear;
var PassHolderSearchClear = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpasssearchviewSeasonpassse.groupSearchgroup.groupHgroup4208.selectablebuttonClearbtn;
//var SearchButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpasssearchviewSeasonpassse.groupSearchgroup.groupHgroup2142.selectablebuttonSearchbtn;
var SearchButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpasssearchviewSeasonpassse.groupSearchgroup.groupHgroup4208.selectablebuttonSearchbtn;

// Pass processing form search fields

var sessionPassBackbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.groupHgroup5099.sessionPassBackbtn;
var sessionPassProcessbtn =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.groupHgroup5099.sessionPassProcessbtn;
var sessionPassSavebtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.groupHgroup5099.sessionPassSavebtn;
var sessionPassTransferbtn=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpassdetailsviewSeasonpassd.groupHgroup5099.sessionPassTransferbtn;
var datagridPassholdersdg=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.seasonpasssearchviewSeasonpassse.groupSearchgroup.groupVgroup4494.datagridPassholdersdg



var buttonClosebutton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ValidateTicketsPopUp.buttonClosebutton;


var CashButton=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupHgroup2658.groupShortcutcontainer.billingshortcutbuttonCash;
var CreditCardButton=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupHgroup2658.groupShortcutcontainer.billingshortcutbuttonCreditCard;

var textinputPromocodeinput =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.groupHeadergroup.groupGroup105.promocodesearchPromosearch.textinputPromocodeinput;
var selectablebuttonSearchbutton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.TopControlBar.groupHeadergroup.groupGroup105.promocodesearchPromosearch.selectablebuttonSearchbutton;

var testPromoCodeCloseImg =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupLeftgroup.keywordlistview.groupKeywordsgrp.groupKeywordlistgroup.Keyword_Listgroup_updated.listitemTest.testPromoCodeCloseImg;



var cashliftalertpopupCashLift=Aliases.Passport_POS.wndApolloRuntimeContentWindow.cashliftalertpopupCashLift
var cashLiftPopupClosebutton =Aliases.Passport_POS.wndApolloRuntimeContentWindow.cashliftalertpopupCashLift.cashLiftPopupClosebutton;


//Credit card
var CC_EnterNumber_old = passportPOS.PaymentType_PaymentStack.CC_EnterNumber;
var CC_EnterNumber = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.creditcardpaymentformCreditCard.groupBordergroup.groupMaincntr.groupVgroup2629.groupHgroup2631.selectablebuttonEntercardnumberb;

var CreditCardPopUp=wnd.CreditCardNumberPopup; 
var Num0=CreditCardPopUp.Num0;
var Num1=CreditCardPopUp.listwithoutkeyboardNumgroup.Num1;
var Num2=CreditCardPopUp.listwithoutkeyboardNumgroup.Num2;
var Num3=CreditCardPopUp.listwithoutkeyboardNumgroup.Num3;
var Num4=CreditCardPopUp.listwithoutkeyboardNumgroup.Num4;
var Num5=CreditCardPopUp.listwithoutkeyboardNumgroup.Num5;
var Num6=CreditCardPopUp.listwithoutkeyboardNumgroup.Num6;
var Num7=CreditCardPopUp.listwithoutkeyboardNumgroup.Num7;
var Num8=CreditCardPopUp.listwithoutkeyboardNumgroup.Num8;
var Num9=CreditCardPopUp.listwithoutkeyboardNumgroup.Num9;

var CC_ExpirationMonth_old = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.CC_ExpirationMonth;
var CC_ExpirationYear_old = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.CC_ExpirationYear;
var CC_ExpirationMonth = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.creditcardpaymentformCreditCard.groupBordergroup.groupMaincntr.groupVgroup2629.groupHgroup2648.dropdownlistCreditexpirationmont;
var CC_ExpirationYear = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.creditcardpaymentformCreditCard.groupBordergroup.groupMaincntr.groupVgroup2629.groupHgroup2648.dropdownlistCreditexpirationyear;



var CC_StreetAddress_old =passportPOS.PaymentType_PaymentStack.CC_StreetAddress;
var CC_ZipCode_old =passportPOS.PaymentType_PaymentStack.CC_ZipCode;
var CC_StreetAddress = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.creditcardpaymentformCreditCard.groupBordergroup.groupMaincntr.groupVgroup2629.groupHgroup2652.textinputCardstreetti;
var CC_ZipCode = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.creditcardpaymentformCreditCard.groupBordergroup.groupMaincntr.groupVgroup2629.groupHgroup2655.textinputCardzipti;
/*var ccMonthlErrorindicator =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.groupGroup4896.creditcardpaymentformCreditcardp.groupBordergroup.groupMaincntr.groupVgroup4698.groupHgroup4717.dropdownlistCreditexpirationmont.bitmap0;
var streetAddErrorindicator = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.groupGroup4896.creditcardpaymentformCreditcardp.groupBordergroup.groupMaincntr.groupVgroup4698.groupHgroup4721.textinputCardstreetti.bitmap0;
var zipCodeErrorindicator =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.groupGroup4896.creditcardpaymentformCreditcardp.groupBordergroup.groupMaincntr.groupVgroup4698.groupHgroup4724.textinputCardzipti.bitmap0;
var ccYearErrorindicator =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.accviewstackPaymentstack.groupGroup4896.creditcardpaymentformCreditcardp.groupBordergroup.groupMaincntr.groupVgroup4698.groupHgroup4717.dropdownlistCreditexpirationyear.bitmap0;*/
var ccMonthlErrorindicator =CC_ExpirationMonth.bitmap0;
var streetAddErrorindicator = CC_StreetAddress.bitmap0;
var zipCodeErrorindicator =CC_ZipCode.bitmap0;
//var ccYearErrorindicator =CC_ExpirationYear.bitmap0;


// Invoice 
var Invoice_Ordernumber_old =passportPOS.PaymentType_PaymentStack.Invoice_Ordernumber;
var Invoice_Organization_old =passportPOS.PaymentType_PaymentStack.Invoice_Organization;
var Invoice_Ordernumber = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.invoicepaymentformTitleLabel.groupBordergroup.groupMaincntr.groupHgroup2703.textinputOrdernumberti;
var Invoice_Organization = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.invoicepaymentformTitleLabel.groupBordergroup.groupMaincntr.groupHgroup2706.textinputOrganizationti;
// Check
var Check_Checknumber_old = passportPOS.PaymentType_PaymentStack.Check_Checknumber;
var Check_name_old = passportPOS.PaymentType_PaymentStack.Check_name;

var Check_Checknumber =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.checkpaymentformTitleLabel.groupBordergroup.groupMaincntr.groupHgroup2714.textinputChecknumberti;
var Check_name = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.checkpaymentformTitleLabel.groupBordergroup.groupMaincntr.groupHgroup2717.textinputChecknameti ;

// Ticket 
var Ticket_TicketBarcode=passportPOS.PaymentType_PaymentStack.Ticket_TicketBarcode;
var Ticket_GetValueButton=passportPOS.PaymentType_PaymentStack.CC_EnterNumber;

// Voucher
var Voucher_Code_old = passportPOS.PaymentType_PaymentStack.Voucher_Code;
var Voucher_Code = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.groupGroup2652.groupVgroup2654.groupGroup2655.groupVgroup2657.groupPaymentstack.voucherpaymentformTitleLabel.groupBordergroup.groupMaincntr.groupHgroup2739.textinputCodeti;




///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var validateTicketspopUp=wnd.ValidateTicketsPopUp;
var CreditCardPopUp=wnd.CreditCardNumberPopup; 



var listitemPromoCodes = passportPOS.listListgroup.listitemPromoCodes;

var alertInfo = wnd.alertInfo;
var alertInfobuttonOk = wnd.alertInfo.alertform0.alertInfobuttonOk;
var postordercharaczippopupAdditiona = wnd.postordercharaczippopupAdditiona;
var zipCodeContinueButton =wnd.postordercharaczippopupAdditiona.zipCodeContinueButton;
var zipCodeTextInput =wnd.postordercharaczippopupAdditiona.zipCodeTextInput;
//Save file window

var dlgSaveTheFileAs = Aliases.POSPrint.dlgSaveTheFileAs;
var btnSaveFile =Aliases.POSPrint.dlgSaveTheFileAs.btnSaveFile;
var editFileNameTextBox =dlgSaveTheFileAs.DUIViewWndClassName.Explorer_Pane.FloatNotifySink.ComboBox.editFileNameTextBox;


var mainMenuHeaderText = passportPOS.POSGroup.groupContentgroup.mainviewMainview33.topcontrolbarTopcontrolbar97.groupControlbar.mainMenuHeaderText;
var noPackagesFound = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.NoPackagesFound;

//Time
var launchClockLabel = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.loginviewLoginview307.groupGroup316.loginpanelclockLpclock.groupHgroup318.labelClocklabel;
var launchampm = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.launchampm;
var launchtimehour = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.launchtimehour;
var launchtimeminute = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.launchtimeminute;
var LogOutActivityWindow =Aliases.Passport_POS.wndApolloRuntimeContentWindow.LogOutActivityWindow;
var youhavebeenloggedout =Aliases.Passport_POS.wndApolloRuntimeContentWindow.LogOutActivityWindow.youhavebeenloggedout;
var inactivityDetectedWindow = Aliases.Passport_POS.wndApolloRuntimeContentWindow.LogOutActivityWindow.inactivityDetectedWindow




 
//Support Manager :

var SupportmanagerPasswordTextBox =passportPOS.Supportmanager.loginpanel.username.SupportmanagerPasswordTextBox;
var SupportmanagerUsernameTextBox =passportPOS.Supportmanager.loginpanel.username.SupportmanagerUsernameTextBox;
var SupportmanagerLoginButton =passportPOS.Supportmanager.loginpanel.SupportmanagerLoginButton;
var smOrdersearchbutton = passportPOS.Supportmanager.smOrdersearchbutton;
var ConfirmationSearchtextBox = passportPOS.Supportmanager.OrderSearchWindow.OrdersearchPanel.ConfirmationSearchtextBox;
var PerformSearchButton = passportPOS.Supportmanager.OrderSearchWindow.PerformSearchButton;
var smCreateprofilebutton =passportPOS.Supportmanager.smCreateprofilebutton;
var smEmailtemplatebutton= passportPOS.Supportmanager.smEmailtemplatebutton;
var smEventsearchbutton = passportPOS.Supportmanager.smEventsearchbutton;
var smProfilesearchbutton =passportPOS.Supportmanager.smProfilesearchbutton;
var smOrderSearchTabBar = passportPOS.Supportmanager.OrderDetailsPageSummary.smOrderSearchTabBar;
var smDatagridTicketdetails =passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.ticketdetailspanel.smDatagridTicketdetails
var smOrderSearchWindow = passportPOS.Supportmanager.OrderSearchWindow;

var newOrdersearchpanelOrderSearch = wnd.newOrdersearchpanelOrderSearch;
var newConfirmationSearchtextBox = newOrdersearchpanelOrderSearch.formOrdersearchpanelForm1.newConfirmationSearchtextBox;
var newPerformSearchButton = newOrdersearchpanelOrderSearch.newPerformSearchButton;
var newCancelButton = newOrdersearchpanelOrderSearch.newCancelButton;
var smDeselectAllUnusedTicketsbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ticketspanelRefund.smDeselectAllUnusedTicketsbtn;
var smSelectAllUnusedTicketsbtn  = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ticketspanelRefund.smSelectAllUnusedTicketsbtn;
var smRefundChangebtn =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ticketspanelRefund.smRefundChangebtn;
var smPartialRefundCnfCancelbtn =Aliases.Passport_POS.wndApolloRuntimeContentWindow.partialrefundconfirmationpanelCo.smPartialRefundCnfCancelbtn;
var smPartialRefundCnfOKbtn = Aliases.Passport_POS.wndApolloRuntimeContentWindow.partialrefundconfirmationpanelCo.smPartialRefundCnfOKbtn;
//order search all tab names in support manager
var tabSummary = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabSummary;
var tabAddressDetails = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabAddressDetails;
var tabCaseNotes = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabCaseNotes;
var tabOrderDetails = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabOrderDetails;
var tabPaymentDetails = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabPaymentDetails;
var tabTicketDetails = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabTicketDetails;
var smCaseNotesdatagridCallhistory =passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.canvasCaseNotes.panelCaseNotes.smCaseNotesdatagridCallhistory;
var smConfirmationOrderNumber = passportPOS.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.smConfirmationOrderNumber;
var ticketBarCodeValue =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.supportmanagerhostSupportmanager.wfloaderSupportmngr.supportmanagerSupportmanager2140.dividedboxDivideddisplay.orderdetailscanvasBostonLegoland.ticketdetailspanel.datagridTicketdetailgridDg.listbasecontentholder0.ticketBarCodeValue;
var cancelOrderTicketDetailsSM = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.ticketdetailspanel.canvasScrollcontainer.groupVgroup8626.datagridTicketrezdetailgridDg.listbasecontentholder0.cancelOrderTicketDetailsSM;
var tabReservationDetails = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.tabbar.tabReservationDetails;
var memotextSupportManagerResDetails = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.Supportmanager.OrderDetailsPageSummary.orderdetailscanvasSM.orderdetailstabReservationdetail.datagridGroupsalesdetailsDg.listbasecontentholder0.memotextSupportManagerResDetails;

// Header Quantity  Buttons

var qty_0=passportPOS.qty_0;
var qty_1=passportPOS.qty_1;
var qty_2=passportPOS.qty_2;
var qty_3=passportPOS.qty_3;
var qty_4=passportPOS.qty_4;
var qty_5=passportPOS.qty_5;
var qty_qty=passportPOS.qty_qty;

var zeroQtyButtonHighlighted = passportPOS.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupGroup212.packagequantityselector.selectablebuttonQtybtn0.groupMaincntr.graphiciconsIconvector.zeroQtyButtonHighlighted;
var zeroQtyButtonNotHighlighted =passportPOS.POSGroup.groupContentgroup.mainviewMainview33.pointofsalePointofsale203.groupHgroup204.groupGroup212.packagequantityselector.selectablebuttonQtybtn0.groupMaincntr.graphiciconsIconvector.zeroQtyButtonNotHighlighted;

// Header QuantityRegisterWindow Buttons
var qtyregister_0=wnd.quantityregisterWindow.qtyregister_0;
var qtyregister_1=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_1;
var qtyregister_2=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_2;
var qtyregister_3=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_3;
var qtyregister_4=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_4;
var qtyregister_5=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_5;
var qtyregister_6=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_6;
var qtyregister_7=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_7;
var qtyregister_8=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_8;
var qtyregister_9=wnd.quantityregisterWindow.listwithoutkeyboardNumericinputd.qtyregister_9;
//var allPackages = passportPOS.allPackages;
//  var allPackages = Sys.Process("Passport POS").Window("ApolloRuntimeContentWindow", "accesso Passport POS", 1).PassportPOS(0).Group(0).Group("contentGroup").MainView(0).PointOfSale(0).HGroup(0).Group("leftGroup").VGroup("packageXmcGroup").PackageListView("packageListView").List("packageListGroup");

//allPackages.listitemPAssocKeywordsReservatio.DataGroup("ratesList").Child()


var settlement_TotalValue = orderDetailsTotal;

var selectablebuttonAddnotes =Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.settlementviewSettlementview7553.groupHgroup75711.selectablebuttonAddnotes;

var popupOrderNotes = Aliases.Passport_POS.wndApolloRuntimeContentWindow.popupOrderNotes;
var orderNotespopupCancel =popupOrderNotes.orderNotespopupCancel;
var orderNotespopupSave =popupOrderNotes.orderNotespopupSave;
var orderNotesPopupTextArea =popupOrderNotes.orderNotesPopupTextArea;
var textareaOrdermemo = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.textareaOrdermemo;
var applycashrespopupCashPayment =wnd.applycashrespopupCashPayment;
var applycashrespopupCashPaymentOKButton = wnd.applycashrespopupCashPayment.applycashrespopupCashPaymentOKButton;
var applycashrespopupCashPaymentinputtext = wnd.applycashrespopupCashPayment.applycashrespopupCashPaymentinputtext;

var settlementOrderDataGridOrderdgRender = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.settlementPageOrderDataGrid.scroller.grid.accdatagridskininnerclass9Accdat.gridlayerRendererlayer;//passportPOS.orderdatagridOrderdg.scroller.grid.accdatagridskininnerclass9Accdat.gridlayerRendererlayer;
var settlementPageOrderDataGrid = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.settlementPageOrderDataGrid;
//var totalAmountSettlement =passportPOS.TotalBalanceLabel_orderDetails.totalAmountSettlement;


var buttonDecrementbutton =scrollbarVerticalscrollbar.buttonDecrementbutton;
var buttonIncrementbutton = scrollbarVerticalscrollbar.buttonIncrementbutton;
var buttonThumb = scrollbarVerticalscrollbar.buttonThumb;

//Groups Window
var groupsSerarchButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupsearchviewGroupsearchview20.groupVgroup2079.groupGroup2080.groupSearchggroupcntr.groupHgroup2116.groupHgroup2120.selectablebuttonSearchbtn;
var groupsClearButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupsearchviewGroupsearchview20.groupVgroup2079.groupGroup2080.groupSearchggroupcntr.groupHgroup2116.groupHgroup2120.selectablebuttonClearbtn;
var groupsCreateButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupsearchviewGroupsearchview20.groupVgroup2079.groupGroup2080.groupSearchggroupcntr.groupHgroup2116.groupHgroup2120.selectablebuttonCreatebtn;
var groupsGride = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupsearchviewGroupsearchview20.groupVgroup2079.groupGroup2139.groupVgroup2141.datagridGroupsdg;

var groupSearchGroupNameHeader=Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.datagridGroupsdg.groupSearchGroupNameHeader;

var groupsNameti = passportPOS.textinputGroupnameti;
var groupsOrganizationNameti  = passportPOS.textinputOrgnameti;
var groupsPhoneti  = passportPOS.textinputPhoneti;
var groupsZipCodeti  = passportPOS.textinputZipti;
var groupsContactEmailti  = passportPOS.textinputContactemailti;
var groupsContactFirstti  = passportPOS.textinputContactfirstti;
var groupsContactLastti = passportPOS.textinputContactlastti;
var groupsReservationidti = passportPOS.textinputReservationid;

//Create group 

var saveNewGroup = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.groupcreateviewGroupcreateview26.groupHgroup2680.groupGroup2233.groupLeftsectioncntr.groupHgroup2241.newGroupSaveButton;
var createNewGroupTabBar = passportPOS.createNewGroupTabBar; 
var accdropdownlistCategoryddl = passportPOS.navigatorcontentGroupDetails.accdropdownlistCategoryddl;
var countriesdropdownlistHomecountry = passportPOS.navigatorcontentGroupDetails.countriesdropdownlistHomecountry;
var dropdownlistStateddl= passportPOS.navigatorcontentGroupDetails.dropdownlistStateddl;
var textinputGroupaddyti= passportPOS.navigatorcontentGroupDetails.textinputGroupaddyti;
var textinputGroupcityti= passportPOS.navigatorcontentGroupDetails.textinputGroupcityti;
var textinputGroupcountyti= passportPOS.navigatorcontentGroupDetails.textinputGroupcountyti;
var textinputGroupidentifierti= passportPOS.navigatorcontentGroupDetails.textinputGroupidentifierti;
var textinputGroupnameti= passportPOS.navigatorcontentGroupDetails.textinputGroupnameti;
var textinputGroupphoneti= passportPOS.navigatorcontentGroupDetails.textinputGroupphoneti;
var textinputGroupzipti= passportPOS.navigatorcontentGroupDetails.textinputGroupzipti;
var textinputOrgnameti= passportPOS.navigatorcontentGroupDetails.textinputOrgnameti;

var textinputPrimaryaltti =  passportPOS.navigatorcontentPrimaryContact.textinputPrimaryaltti;
var textinputPrimaryemailti =  passportPOS.navigatorcontentPrimaryContact.textinputPrimaryemailti;
var textinputPrimaryfirstti=  passportPOS.navigatorcontentPrimaryContact.textinputPrimaryfirstti;
var textinputPrimarylastti=  passportPOS.navigatorcontentPrimaryContact.textinputPrimarylastti;
var textinputPrimaryphoneti=  passportPOS.navigatorcontentPrimaryContact.textinputPrimaryphoneti;

//Group Update Page

//var groupUpdateSearchButton = passportPOS.qty_1 ;
var groupUpdateSvaeButton = passportPOS.qty_0 ;
var groupUpdateDatagridOrderHistory = passportPOS.datagridOrderhistorydg;

var groupUpdateDataGridReservation = passportPOS.datagridRezhistorydg;

var dataGridResDateTimeHeader =passportPOS.datagridRezhistorydg.dataGridResDateTimeHeader;
var dateTimeArrowIndicator =passportPOS.datagridRezhistorydg.groupVgroup1760.gridcolumnheadergroupColumnheade.gridcolumnheaderviewGridcolumnhe.groupGroup1822.accdatagridskininnerclass4DateTi.groupHgroup1871.dateTimeArrowIndicator

var dataGridOrderDateTimeHeader = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.datagridOrderhistorydg.dataGridOrderDateTimeHeader;


//cart item list


var listitemPAssocKeywordsDailyAdmis =passportPOS.cartaddedItemList.listitemPAssocKeywordsDailyAdmis;

var datagroupRateslistItems =listitemPAssocKeywordsDailyAdmis.datagroupRateslistItems;
var labelExtralabel = listitemPAssocKeywordsDailyAdmis.labelExtralabel;
//Order infor Reservation Window
var  orderRefundButton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.orderinfopopupReservation.groupGroup8232.groupContents.groupGroup8240.groupContentgroup.groupOrderbuttongroup.groupVgroup8260.selectablebuttonRefundbtn;
var  reservationWndAddReservation= wnd.orderinfopopupReservation.reservationWndAddReservation;
var  reservationWndCancelRefund= wnd.orderinfopopupReservation.reservationWndCancelRefund;
var  reservationWndCancelReservation= wnd.orderinfopopupReservation.reservationWndCancelReservation;
var  reservationWndCancelSelectedTickets = wnd.orderinfopopupReservation.reservationWndCancelSelectedTickets;
var  reservationWndLoadReservation= wnd.orderinfopopupReservation.reservationWndLoadReservation;
var  reservationWndModifyReservationDate= wnd.orderinfopopupReservation.reservationWndModifyReservationDate;
var  reservationWndPartialRefundReservation= wnd.orderinfopopupReservation.reservationWndPartialRefundReservation;
var  reservationWndReprintReceipt= wnd.orderinfopopupReservation.reservationWndReprintReceipt;

var  checkboxReservationOrder = wnd.orderinfopopupReservation.orderinfoResDataGrid.scroller.checkboxReservationOrder;
var  checkboxReservationOrderRow2 = wnd.orderinfopopupReservation.orderinfoResDataGrid.scroller.checkboxReservationOrderRow2;
var  orderinfoResDataGridScroller = wnd.orderinfopopupReservation.orderinfoResDataGrid.scroller;
var  reservationWndmemoText = wnd.orderinfopopupReservation.reservationWndmemoText;
var  orderinfoResDataGrid = wnd.orderinfopopupReservation.orderinfoResDataGrid; 
var  cancelSelectedOK = wnd.orderselecteditemspopupCancelSel.cancelSelectedOK;
var  cancelSelectedInputText = wnd.orderselecteditemspopupCancelSel.datagridOrderitems.scroller.cancelSelectedInputText;
var  resOrderInfoClosebutton = wnd.orderinfopopupReservation.resOrderInfoClosebutton;
var orderinfopopupReservation =Aliases.Passport_POS.wndApolloRuntimeContentWindow.orderinfopopupReservation;
var orderWndRefund = wnd.orderinfopopupReservation.orderWndRefund;
var orderWndReprintSelectedTickets = wnd.orderinfopopupReservation.orderWndReprintSelectedTickets;
var resPartialPaymentAmountinput = wnd.partialrefundamountpopupPartialR.resPartialPaymentAmountinput;
var resPartialPaymentOkButton = wnd.partialrefundamountpopupPartialR.resPartialPaymentOkButton;
var resPartialPaymentPaidAmt = wnd.partialrefundamountpopupPartialR.resPartialPaymentPaidAmt;

var reservationoverpaymentrefundpopu = Aliases.Passport_POS.wndApolloRuntimeContentWindow.reservationoverpaymentrefundpopu;
var resUpdateDoneButton = wnd.reservationoverpaymentrefundpopu.resUpdateDoneButton;
var resUpdatetextinputBillingaddressti1 = wnd.reservationoverpaymentrefundpopu.resUpdatetextinputBillingaddressti1;
var resUpdatetextinputBillingaddressti2= wnd.reservationoverpaymentrefundpopu.resUpdatetextinputBillingaddressti2;
var resUpdatetextinputFirstnameti = wnd.reservationoverpaymentrefundpopu.resUpdatetextinputFirstnameti;
var resUpdatetextinputLastnameti = wnd.reservationoverpaymentrefundpopu.resUpdatetextinputLastnameti;
var reservationoverpaymentrefundpopupClosebutton =  wnd.reservationoverpaymentrefundpopu.reservationoverpaymentrefundpopupClosebutton;
var OK = wnd.reservationoverpaymentrefundpopu.OK;

var alertCancelReservation = wnd.alertCancelReservation;
var alertCancelReservationNo = alertCancelReservation.alertCancelReservationNo;
var alertCancelReservationYes = alertCancelReservation.alertCancelReservationYes;
var errorindicatorCancelTicket = Aliases.Passport_POS.wndApolloRuntimeContentWindow.authorizationpopupRefundReservat.refundReservationConfReasontext.errorindicatorCancelTicket;
var alertOk = Aliases.Passport_POS.wndApolloRuntimeContentWindow.alertCancelReservation.alertOk;
//Order cancel and refund Reservation Window
var cancelARefundEditDetails = wnd.reservationoverpaymentrefundpopu.Edit_Details
var cancelARefundOk = wnd.reservationoverpaymentrefundpopu.OK;
var richtextRichtext = wnd.reservationoverpaymentrefundpopu.richtextRichtext;

var authorizationpopupRefundReservat = wnd.authorizationpopupRefundReservat;
var refundReservationConf = wnd.authorizationpopupRefundReservat.refundReservationConf;
var refundReservationConfOK = wnd.authorizationpopupRefundReservat.refundReservationConfOK;
var refundReservationConfPassword = wnd.authorizationpopupRefundReservat.refundReservationConfPassword;
var refundReservationConfReasontext = wnd.authorizationpopupRefundReservat.refundReservationConfReasontext;
var refundReservationClosebutton = wnd.authorizationpopupRefundReservat.refundReservationClosebutton;
//Reservation Modify Date popup
var modifyreservationdatepopupModify = wnd.modifyreservationdatepopupModify;
var resModifyDateOkButton =    modifyreservationdatepopupModify.resModifyDateOkButton; 
var resModifyDateCancelButton = modifyreservationdatepopupModify.resModifyDateCancelButton;
var resModifyDateCalendarIcon = modifyreservationdatepopupModify.resModifyDateCalendarIcon;
var resModifyDatetextinputDate = modifyreservationdatepopupModify.resModifyDatetextinputDate;           
var resModifyDateTimelist = modifyreservationdatepopupModify.groupGroup7972.groupContents.groupGroup7979.groupContentgroup.groupVgroup7985.groupHgroup7986.bordercontainerBordercontainer91.resModifyDateTimelist;
//var resModifyDatetextinput = modifyreservationdatepopupModify.groupGroup7972.groupContents.groupGroup7979.groupContentgroup.groupVgroup7985.groupHgroup7986.groupVgroup7987.groupVgroup7989.resModifyDateCalendarpopup.resModifyDatetextinput
var dt = aqDateTime.SetDateElements(2018,03, 20);; 
var dateD = aqConvert.DateTimeToFormatStr(dt, "%#m/%#d/%Y");
var newD = aqDateTime.AddDays(dateD, 1); 
var resModifyDatetextinputDateString =  "03 / 2   0  /       2     0     1     8";
//settlement page order details 
var orderDetails = passportPOS.TotalBalanceLabel_orderDetails.groupDetailsvgroup;
var cartdetailsCartfeedetails = orderDetails.cartdetailsCartfeedetails;
var orderDetailsCartAdjustment = orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupCartAdjustment.orderDetailsCartAdjustment;
var orderDetailsFees =orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupFees.orderDetailsFees;
var orderDetailsTax =orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupTax.orderDetailsTax;
var orderDetailsMinimumPayment =orderDetails.groupMiniumPayment.orderDetailsMinimumPayment;
var orderDetailsSubTotal =orderDetails.groupSubTotal.orderDetailsSubTotal;
var orderDetailsTotal =orderDetails.groupTotal.orderDetailsTotal;
 
//Concierge package window
var mcformwrapperConciergePackageAdu= passportPOS.mcformwrapperConciergePackageAdu; 
var conciergePklabelNext = mcformwrapperConciergePackageAdu.conciergePklabelNext;
var conciergePktextinput = mcformwrapperConciergePackageAdu.conciergePktextinput;
var labelSettlement = passportPOS.labelSettlement;
var labelPointOfSale =passportPOS.labelPointOfSale;
var labelGroupSearch = passportPOS.labelGroupSearch;
var labelPassholderSearch = passportPOS.labelPassholderSearch;

var mcformwrapperNyPassPackageAdultE= passportPOS.mcformwrapperNyPassPackageAdultE; 
var NYPassValidationtextinput = mcformwrapperNyPassPackageAdultE.NYPassValidationtextinput;

//confirmation page order details 

var cnf_orderDetails = passportPOS.confirmationPageOrderDetails.groupDetailsvgroup;
var cnf_orderDetailsCartAdjustment = cnf_orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupCartAdjustment.cnf_orderDetailsCartAdjustment;
var cnf_orderDetailsFees =cnf_orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupFees.cnf_orderDetailsFees;
var cnf_orderDetailsTax =cnf_orderDetails.cartdetailsCartfeedetails.groupInsideCart.groupTax.cnf_orderDetailsTax;
var cnf_orderDetailsSubTotal =cnf_orderDetails.groupSubTotal.cnf_orderDetailsSubTotal;
var cnf_orderDetailsTotal = cnf_orderDetails.groupTotal.cnf_orderDetailsTotal;
var cnf_orderID =  passportPOS.cnf_orderID;
var cnf_orderID1 = passportPOS.cnf_orderID1;
var ConfirnScreenOrderID=passportPOS.ConfirnScreenOrderID;
var settlementPageOrderDataGrid = passportPOS.settlementPageOrderDataGrid;
var listCarttotalspaymentlist = passportPOS.confirmationPageOrderDetails.groupDetailsvgroup.listCarttotalspaymentlist;
var Cnflabel_InvoicePaymentType = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupGroup6424.carttotalsviewOrdertotals.groupVgroup3649.scrollerScrollbar.groupDetailsvgroup.listCarttotalspaymentlist.listitemObjectObject.groupGroup3741.labelInvoice;

// confirmation page amount details
//var confirmationSubTotal = passportPOS.confirmationPage.confirmationSubTotal;
//var confirmationTotal = passportPOS.confirmationPage.confirmationTotal;
// Order Detail Total balance
//var labelTotal=passportPOS.labelTotal;   
// Balance label

//Tracker popup Sacn and validate
//authorizationpopup
var authorizationpopupOk = wnd.authorizationpopupAuthorizationR.authorizationpopupOk;
var authorizationpopupPasswordtext = wnd.authorizationpopupAuthorizationR.authorizationpopupPasswordtext;
var authorizationpopupUsernametext = wnd.authorizationpopupAuthorizationR.authorizationpopupUsernametext;

//alert window
var alertErrorWnd = wnd.alertError;
var alertErrorbuttonOk =wnd.alertError.alertform0.alertErrorbuttonOk;
var errorWindow = wnd.InvalidLoginErrorWindow;
var buttonOkOnError = wnd.InvalidLoginErrorWindow.buttonOkOnError;
var errorMessagedisplay = wnd.InvalidLoginErrorWindow.errorMessagedisplay;

var trackerpopupTrackerScanAndValida = wnd.trackerpopupTrackerScanAndValida;
var trackerScanBarcodeInput = trackerpopupTrackerScanAndValida.trackerScanBarcodeInput;
var trackerScanLogout = trackerpopupTrackerScanAndValida.trackerScanLogout;
var trackerScanValidate = trackerpopupTrackerScanAndValida.trackerScanValidate;
var trackerScanCloseButton = trackerpopupTrackerScanAndValida.trackerScanCloseButton;
var DeviceIDErrorLabel = wnd.trackerpopupTrackerScanAndValida.groupGroup5826.groupContents.groupGroup5833.groupContentgroup.groupVgroup5897.DeviceIDErrorLabel;
var trackerScanDeviceidInput =  trackerpopupTrackerScanAndValida.trackerScanDeviceidInput;
var selectablebuttonOverridebutton =Aliases.Passport_POS.wndApolloRuntimeContentWindow.trackerpopupTrackerScanAndValida.groupGroup5826.groupContents.groupGroup5833.groupContentgroup.groupVgroup5897.selectablebuttonOverridebutton;


 
var PayamountTextBox=passportPOS.PayamountTextBox;




var labelSubtotal=passportPOS.TotalBalanceLabel_orderDetails.labelSubtotal;
var labelFee=passportPOS.TotalBalanceLabel_orderDetails.labelFee;
//var labelTax=passportPOS.TotalBalanceLabel_orderDetails.labelTax;
var TotalValue=passportPOS.TotalBalanceLabel_orderDetails.TotalValue;
var labelCartadjustment=passportPOS.TotalBalanceLabel_orderDetails.labelCartadjustment;

var CartAdustmentValue=passportPOS.TotalBalanceLabel_orderDetails.CartAdustmentValue;
var FeeValue =passportPOS.TotalBalanceLabel_orderDetails.FeeValue;
var TaxValue =passportPOS.TotalBalanceLabel_orderDetails.TaxValue;
var SubtotalValue =passportPOS.TotalBalanceLabel_orderDetails.SubtotalValue;


//Calender objects
//var datetimeform2SiteCombiWith2Fee= wnd.datetimeform2SiteCombiWith2Fee;
//var datetimeformDated= wnd.datetimeformDated;
//var wildNm=datetime+"*"+"";
//var datetimeWild= wnd.datetimeformDated;
//var datetimeformDateTime= wnd.datetimeformDateTime;

// Payment Type Frame
var Settlement_AdjustBalance=passportPOS.Settlement_AdjustBalance;
var Settlement_CompleteOrder=passportPOS.Settlement_CompleteOrder;
var Settlement_CustomerDetails=passportPOS.Settlement_CustomerDetails;
var applyButton=passportPOS.PaymetType_ApplyButton;
var applyBalance=passportPOS.PaymetType_ApplyBalance;

var cashButtonsOnSettlement = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.PaymentType_PaymentStack.cashButtonsOnSettlement;






// Validate PopUp
var ValidateAllButton= validateTicketspopUp.ValidateAllButton;
var ValidateSelectedButton=validateTicketspopUp.ValidateSelectedButton;
var DontValidateButton=validateTicketspopUp.DontValidateButton;
var listTicketsGroup = validateTicketspopUp.listTicketsGroup;
//New Order button
var NewOrder_Button=passportPOS.NewOrder_Button;
var PassProcessing_Button=passportPOS.confirmation_PassProcessing;


var news; 
var  intr = 10;
var ValidateAllButton       = validateTicketspopUp.ValidateAllButton;
var ValidateSelectedButton  = validateTicketspopUp.ValidateSelectedButton;
var DontValidateButton      = validateTicketspopUp.DontValidateButton;
var ValidateFailed_Alert    = wnd.ValidateFailed_Alert;
var ValidateFailed_AlertOK  = wnd.ValidateFailed_Alert.ValidateFailed_AlertOK;

// Passholder detials
var PassholderWindow = passportPOS.PassholderWindow;
var Address      = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Address;
var Address2     = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Address2;
var AltPhone     = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.AltPhone;
var City_Town    = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.City_Town;
var Country      = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Country;
var DateOfBirth  = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.DateOfBirth;
var Email        = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Email;
var ExternalID   = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.ExternalID;
var FirstName    = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.FirstName;

//var Gender       = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Gender;
var Gender       = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.groupGroup2266.groupVerticalformgroup.groupHgroup2305.groupGroup2317.dropdownlistGenderddl;
var LastName     = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.LastName;

var MiddleInitial= passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.MiddleInitial;
var Phone        = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Phone;
var State        = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.State;
var SubscriptionTOEmailBlast = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.SubscriptionTOEmailBlast;
var Suffix       = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Suffix;
var ZipCode      = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.ZipCode;
var Memo         = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Memo.MemoBorder.MemoTextArea;
var MemoTextA    = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.Memo;
var PassholderDetailsClearButton = passportPOS.PassholderWindow.PassholderForm.PassholderFormBorder.PassholderDetailsClearButton;

var Passholder_NextButton= passportPOS.PassholderWindow.Passholder_NextButton;
var PassholderCameraLogo=passportPOS.PassholderWindow.PassholderCamera.PassholderCameraLogo;
var Capture_Button=passportPOS.PassFulfillment_Camera.Capture_Button; 
var ClearCamera_Button=passportPOS.PassFulfillment_Camera.ClearCamera_Button;
var Save_Button=passportPOS.PassFulfillment_Camera.Save_Button;
var Camera_Save_Button=passportPOS.PassFulfillment_Camera.Save_Button;

var NextDollerAmount;

var PassholderWindowListScrollbar = PassholderWindow.groupGroup19412.groupContents.groupGroup19419.groupContentgroup.groupVgroup19425.groupHgroup19427.groupParticipantlistvgroup.PassholderWindowListScrollbar;
var PassholderWindowClosebutton =PassholderWindow.PassholderWindowClosebutton;
var alertWarningbuttonOk =wnd.alertWarning.alertWarningbuttonOk;

var OrderHistory_Scroller_PackageName_Row1         = passportPOS.TotalBalanceLabel_orderDetails.PassHolderSearch_SeasonPassIDWindow.OrderHistoryWindow_DataGrid.OrderHistory_Scroller.OrderHistory_Scroller_PackageName_Row1;  
var OrderHistory_Scroller_StatusField_Row1         = passportPOS.TotalBalanceLabel_orderDetails.PassHolderSearch_SeasonPassIDWindow.OrderHistoryWindow_DataGrid.OrderHistory_Scroller.OrderHistory_Scroller_StatusField_Row1;








var Pass_Fulfillment                               = passportPOS.Pass_Fulfillment;




var Save_Button = passportPOS.qty_0;
var BuyButton= passportPOS.qty_2;

//var TicketBarcodeTextBox = passportPOS.TotalBalanceLabel_orderDetails.PassHolderSearch_SeasonPassIDWindow.TicketBarcodeTextBox;

// Promo Codes Keyword
PromoCodes_EnterPromoCodes=passportPOS.PromoCodes_EnterPromoCodes;



//Change password
var changePwdcurrentPassword =wnd.changepasswordpopup0.changePwdcurrentPassword;
var changePwdNewPassword =wnd.changepasswordpopup0.changePwdNewPassword;
var changePwdOkButton =wnd.changepasswordpopup0.changePwdOkButton;
var changePwdReenterNewPass =wnd.changepasswordpopup0.changePwdReenterNewPass;
var changePwdClosebutton =wnd.changepasswordpopup0.changePwdClosebutton;
//Refund button
 
//var confirmationChangeDue = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.confirmationChangeDue;
var confirmationChangeDue = Aliases.Passport_POS.wndApolloRuntimeContentWindow.passportposPassportpos1.POSGroup.groupContentgroup.mainviewMainview33.confirmationviewConfirmationview.groupMainvg.groupGroup6424.carttotalsviewOrdertotals.groupVgroup3649.groupChangerefundgroup.confirmationChangeDue;
//Order history popUp
var Orderlist = wnd.OrderHistory_PopUp.Orderlist;
var labelNoOrderHistoryFound =  wnd.OrderHistory_PopUp.labelNoOrderHistoryFound;
var OrderId0       = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata0.ViewOrderButton0.OrderDetails0.OrderId0; 
var OrderStatus0   = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata0.ViewOrderButton0.OrderDetails0.OrderStatus0;
var ViewOrderButton0 =wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata0.ViewOrderButton0.OrderDetails0.OrderStatus0; 


var OrderId1       = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata1.ViewOrderButton1.OrderDetails1.OrderId1; 
var OrderStatus1   = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata1.ViewOrderButton1.OrderDetails1.OrderStatus1;
var ViewOrderButton1 =wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata1.ViewOrderButton1.OrderDetails1.OrderStatus1;


var OrderId2         = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata2.ViewOrderButton2.OrderDetails2.OrderId2; 
var OrderStatus2     = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata2.ViewOrderButton2.OrderDetails2.OrderStatus2;
var ViewOrderButton1 = wnd.OrderHistory_PopUp.Orderlist.OrderHstory_Transactiondata2.ViewOrderButton2.OrderDetails2.OrderStatus2;


var alertErrorInPackage=wnd.alertErrorInPackage;
var buttonOk = wnd.alertErrorInPackage.alertform0.buttonOk;


var AvailableTime_DayMMDDYYYY=wnd.datetimeformSubWindow.AvailableTime_DayMMDDYYYY;
var confirmationPassProcessingButton=passportPOS.confirmation_PassProcessing;
var cnfPrintSeasonPassButton = passportPOS.cnfPrintSeasonPassButton;





var AltField = passportPOS.TotalBalanceLabel_orderDetails.PassHolderDetails.AltField; 
var CountryField = passportPOS.TotalBalanceLabel_orderDetails.PassHolderDetails.CountryField;

var ExternalField = passportPOS.TotalBalanceLabel_orderDetails.PassHolderDetails.ExternalField;






// Settlement Screen
var OrderDetailDateTime_Row1 = passportPOS.settlementPageOrderDataGrid.scroller.OrderDetailDateTime_Row1;
var settlement_scroller =passportPOS.settlementPageOrderDataGrid.scroller;

// Passholder Search select Merchant type DropDown
var Merchantdropdown = passportPOS.Merchantdropdown; 
var FilterButton = passportPOS.qty_0;


// Support Manager Login Window

var supportmanagerUsernameTextBox = passportPOS.Supportmanager.loginpanel.username.SupportmanagerUsernameTextBox;
var supportmanagerPasswordTextBox = passportPOS.Supportmanager.loginpanel.username.SupportmanagerPasswordTextBox;
var OrderSearchWindow = passportPOS.Supportmanager.OrderSearchWindow;

var SupportmanagerLoginButton = passportPOS.Supportmanager.loginpanel.SupportmanagerLoginButton;
var ConfirmationSearchtextBox = passportPOS.Supportmanager.OrderSearchWindow.OrdersearchPanel.ConfirmationSearchtextBox;
var PerformSearchButton = passportPOS.Supportmanager.OrderSearchWindow.PerformSearchButton;
var OrderDetailsPageSummary = passportPOS.Supportmanager.OrderDetailsPageSummary;

var Confirmation_OrderID = passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.Confirmation_OrderID;



// Settlemenet Screen Date/Time

var SettlementScreen_DateTime = passportPOS.SettlementScreen_DateTime;

var OrderHistoryDataGrid=passportPOS.OrderHistoryDataGrid;
var OrderHistoryScroller= passportPOS.OrderHistoryDataGrid.OrderHistoryScroller;



// Order Reservation popup
var DateTime_Row1Value = wnd.OrderReservation_PopUp.StatusDataGrid.StatusDataGridScroller.DateTime_Row1Value

// About Description
var PosVersion = wnd.AboutPOSPopUp.PosVersion;
var CePosVersion = wnd.AboutPOSPopUp.CePosVersion;
var ExternalDeviceVersion = wnd.AboutPOSPopUp.ExternalDeviceVersion;
var PosPrintVersion = wnd.AboutPOSPopUp.PosPrintVersion;
var IslandName = wnd.AboutPOSPopUp.IslandName;
var MerchantName = wnd.AboutPOSPopUp.MerchantName;
var CloseButton = wnd.AboutPOSPopUp.CloseButton;





var PrintMenu =passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.SuppoertManager_Menubar.PrintMenu;
var subMenuPrintTicket =  wnd.RefundSubmenu.subMenuPrintTicket;
var subMenuPrintReceipt = wnd.RefundSubmenu.subMenuPrintReceipt;
var buttonToggleselectallbutton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.selectticketstoprintpanelSelectT.buttonToggleselectallbutton;
var buttonPrintbutton = Aliases.Passport_POS.wndApolloRuntimeContentWindow.selectticketstoprintpanelSelectT.buttonPrintbutton;

var RefundMenu = passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.SuppoertManager_Menubar.RefundMenu;
var RefundSubmenuRefundOrder = wnd.RefundSubmenu.RefundOrder;
var PartialRefundCheckbox = passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.PartialRefundPanel.PartialRefundPanelScroller.PartialRefundPanelRow1.checkbox;
var SelectAllUnusedTicketsButton = passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.PartialRefundPanel.PartialRefundPanelScroller.SelectAllUnusedTicketsButton;
var ChangeButton = passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.PartialRefundPanel.ChangeButton;
var Refund_buttonOk = passportPOS.Supportmanager.OrderDetailsPageSummary.OrderDetails.PanelPartialrefundconfiramationScreen.Refund_buttonOk;
var smRefundOrdercheckbox =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ticketspanelRefund.scrollerScroller5887.smRefundOrdercheckbox;
var ErrorMessageButtonOk = wnd.ErrorMessageOKButton.OKBUtton.buttonOk;
var loginErrorMessage = wnd.InvalidLoginErrorWindow.loginErrorMessage;
// Page Exchange

var pageExchange = wnd.ShellEmbedding.ShellDocObjectView.browser.pageExchange;
var pageExchangebuttonCancel = pageExchange.pageExchangebuttonCancel;
var pageExchangebuttonNext=pageExchange.pageExchangebuttonNext;

var pageExchange2=Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2; 

var textnodeMerlinQa = pageExchange2.panelTradesPortalToolbarTop.textnodeMerlinQa;
var textnodeMenuStore = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelPullRightMenuItemContainer.panelToolbarMenuItemNgScope.textnodeMenuStore;
var panelStoreViewNgScope = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalMainContent.panelStoreViewNgScope;
 
var textnodeMenuReports =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer2.panelToolbarMenuItemNgScope.textnodeMenuReports;
var panelModalContentForReport= Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelModalNgIsolateScopeAcModal.panelModalContainer.panelModalDialogModalStandard.panelModalContentForReport;
var buttonOkReport = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelModalNgIsolateScopeAcModal.panelModalContainer.panelModalDialogModalStandard.panelModalContentForReport.buttonOkReport;
var textnodeMenuRefunds =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer.panelToolbarMenuItemNgScope.textnodeMenuRefunds
var panelReturnsPropertiesView =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalMainContent.panelReturnsPropertiesView;
var panelRefundDetails = panelReturnsPropertiesView.panelRightBorder.panelAcTabsMainContainer.panel.panelRefundDetails

var  textnodeMenuAdmin = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer3.panelToolbarMenuItemNgScope.textnodeMenuAdmin;
var buttonAccountsPayments =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer3.panelToolbarMenuItemNgScope.buttonAccountsPayments;
var buttonLocations =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer3.panelToolbarMenuItemNgScope.buttonLocations;
var buttonProducts = Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer3.panelToolbarMenuItemNgScope.buttonProducts;
var buttonUsers =Aliases.Passport_POS.wndApolloRuntimeContentWindow.ShellEmbedding.ShellDocObjectView.browser.pageExchange2.panelTradesPortalToolbarTop.panelMiddleMenuColXs6.panelPullRightMenuItemContainer3.panelToolbarMenuItemNgScope.buttonUsers;

//cartdetails popup CartDetails
var cartdetailspopupCartDetails =wnd.cartdetailspopupCartDetails;
var cartdetailsClosebutton = cartdetailspopupCartDetails.cartdetailsClosebutton;
var cartdetailsdatagroupAdjlist = cartdetailspopupCartDetails.scrollerScroller3355.groupVgroup3356.cartdetailsdatagroupAdjlist;
var cartdetailsdatagroupFeelist =cartdetailspopupCartDetails.scrollerScroller3355.groupVgroup3356.cartdetailsdatagroupFeelist;
var cartdetailsdatagroupTaxlist = cartdetailspopupCartDetails.scrollerScroller3355.groupVgroup3356.cartdetailsdatagroupTaxlist;
var labelTitledisplay = Aliases.Passport_POS.wndApolloRuntimeContentWindow.cartdetailspopupCartDetails.labelTitledisplay;
 